from __future__ import annotations

from generate_synthetic_data.shared_catalogue import (
    CLINICAL_PREFERENCE_PROFILES,
    CONSUMABLES_ITEMS,
    DISPOSABLES_ITEMS,
    DRESSING_OPTIONS,
    PROCEDURES,
    SPECIAL_INSTRUCTIONS_POOL,
    SPECIALTIES,
    SUBSPECIALTIES,
    SURGEON_NAMES,
    SURGEON_UPDATE_ROLES,
    SUTURE_NAMES,
)

__all__ = [
    "SPECIALTIES",
    "SUBSPECIALTIES",
    "PROCEDURES",
    "CLINICAL_PREFERENCE_PROFILES",
    "SPECIAL_INSTRUCTIONS_POOL",
    "CONSUMABLES_ITEMS",
    "DISPOSABLES_ITEMS",
    "SUTURE_NAMES",
    "DRESSING_OPTIONS",
    "SURGEON_NAMES",
    "SURGEON_UPDATE_ROLES",
]
