from __future__ import annotations

SPECIALTIES = ['Orthopaedics']

SUBSPECIALTIES = {'Orthopaedics': ['Joint Replacement',
                  'Sports Medicine',
                  'Trauma',
                  'Hand Surgery',
                  'Foot and Ankle',
                  'Spine']}

PROCEDURES = {'Foot and Ankle': [{'codes': {'diagnosis': ['M20.10'], 'procedure': ['0LQ54ZZ']},
                     'name': 'MTPJ Fusion',
                     'subspecialty': 'Foot and Ankle'},
                    {'codes': {'diagnosis': ['M25.571'], 'procedure': ['0LQC4ZZ']},
                     'name': 'Ankle Arthroscopy',
                     'subspecialty': 'Foot and Ankle'},
                    {'codes': {'diagnosis': ['M77.41'], 'procedure': ['0LQJ0ZZ']},
                     'name': 'Open Achilles Tendon Repair',
                     'subspecialty': 'Foot and Ankle'}],
 'Hand Surgery': [{'codes': {'diagnosis': ['G56.00'], 'procedure': ['01N60ZZ']},
                   'name': 'Carpal Tunnel Release',
                   'subspecialty': 'Hand Surgery'},
                  {'codes': {'diagnosis': ['M65.331'], 'procedure': ['01N70ZZ']},
                   'name': 'Percutaneous Trigger Finger Release',
                   'subspecialty': 'Hand Surgery'},
                  {'codes': {'diagnosis': ['M18.0'], 'procedure': ['0LPU0ZZ']},
                   'name': 'Thumb Carpometacarpal Joint Arthroplasty',
                   'subspecialty': 'Hand Surgery'}],
 'Joint Replacement': [{'codes': {'diagnosis': ['M17.10'], 'procedure': ['0SRC0JZ']},
                        'name': 'Total Knee Replacement',
                        'subspecialty': 'Joint Replacement'},
                       {'codes': {'diagnosis': ['M16.10'], 'procedure': ['0SRD0JZ']},
                        'name': 'Total Hip Replacement (Cemented)',
                        'subspecialty': 'Joint Replacement'},
                       {'codes': {'diagnosis': ['M19.011'], 'procedure': ['0RRG0JZ']},
                        'name': 'Total Shoulder Replacement',
                        'subspecialty': 'Joint Replacement'},
                       {'codes': {'diagnosis': ['M19.011'], 'procedure': ['0RRG0JZ']},
                        'name': 'Reverse Shoulder Replacement',
                        'subspecialty': 'Joint Replacement'}],
 'Spine': [{'codes': {'diagnosis': ['M48.06'], 'procedure': ['00SN0ZZ']},
            'name': 'Lumbar Laminectomy',
            'subspecialty': 'Spine'},
           {'codes': {'diagnosis': ['M51.26'], 'procedure': ['00SN4ZZ']},
            'name': 'Spinal Microdiscectomy',
            'subspecialty': 'Spine'}],
 'Sports Medicine': [{'codes': {'diagnosis': ['M75.100'], 'procedure': ['0LQ44ZZ']},
                      'name': 'Arthroscopic Rotator Cuff Repair',
                      'subspecialty': 'Sports Medicine'},
                     {'codes': {'diagnosis': ['M75.200'], 'procedure': ['0LQ44ZZ']},
                      'name': 'Arthroscopic Biceps Tenodesis',
                      'subspecialty': 'Sports Medicine'}],
 'Trauma': [{'codes': {'diagnosis': ['S82.40XA'], 'procedure': ['0QS604Z']},
             'name': 'ORIF Tibia and Fibula',
             'subspecialty': 'Trauma'},
            {'codes': {'diagnosis': ['S82.80XA'], 'procedure': ['0QS704Z']},
             'name': 'ORIF Ankle',
             'subspecialty': 'Trauma'},
            {'codes': {'diagnosis': ['S72.00XA'], 'procedure': ['0QS004Z']},
             'name': 'Fixation of fracture of neck of femur using intramedullary nail',
             'subspecialty': 'Trauma'}]}
