from __future__ import annotations

CLINICAL_PREFERENCE_PROFILES = {'Ankle Arthroscopy': {'anaesthetic': 'General Anaesthesia + LMA',
                       'consumables': ['Arthroscopy Fluid 3L', 'Pump Tubing', 'Suction Tubing'],
                       'disposables': ['Arthroscopy Shaver Blade 4.0mm', 'Disposable Trocar Set'],
                       'drape_pack': 'Ankle Arthroscopy Drape Pack',
                       'dressings': ['Mepore', 'Wool and Crepe'],
                       'equipment': ['Arthroscopy stack system with HD camera'],
                       'implant_system': None,
                       'implants': None,
                       'instrument_system': 'Smith & Nephew Dyonics Small Joint Scope Core',
                       'instruments': [{'name': 'Small Joint Arthroscopy Set', 'quantity': 1}],
                       'positioning': 'Supine on standard table with leg holder',
                       'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                       'sutures': ['Nylon 3-0']},
 'Arthroscopic Biceps Tenodesis': {'anaesthetic': 'Interscalene Brachial Plexus Block + Light Sedation',
                                   'consumables': ['Arthroscopy Fluid 3L', 'Pump Tubing', 'Suction Tubing'],
                                   'disposables': ['Arthroscopy Shaver Blade 4.0mm', 'Disposable Cannula Set'],
                                   'drape_pack': 'Shoulder Arthroscopy Drape Pack',
                                   'dressings': ['Opsite Post-Op'],
                                   'equipment': ['Arthroscopy stack system with HD camera'],
                                   'implant_system': 'Arthrex BioComposite Tenodesis Screw Kit',
                                   'implants': ['Tenodesis Screw'],
                                   'instrument_system': 'Arthrex Biceps Tenodesis Master Instrument Tray',
                                   'instruments': [{'name': 'Biceps Tenodesis Kit', 'quantity': 1}],
                                   'positioning': 'Beach chair position',
                                   'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                                   'sutures': ['FiberWire #2', 'SutureTape 1.3mm']},
 'Arthroscopic Rotator Cuff Repair': {'anaesthetic': 'Interscalene Brachial Plexus Block + Light Sedation',
                                      'consumables': ['Arthroscopy Fluid 3L', 'Pump Tubing', 'Suction Tubing'],
                                      'disposables': ['Arthroscopy Shaver Blade 4.0mm', 'Disposable Cannula Set'],
                                      'drape_pack': 'Shoulder Arthroscopy Drape Pack',
                                      'dressings': ['Opsite Post-Op'],
                                      'equipment': ['Arthroscopy stack system with HD camera',
                                                    'Arthrex Synergy UHD4 Imaging Console'],
                                      'implant_system': 'Arthrex SpeedBridge Anchor System',
                                      'implants': ['SutureTape Anchors', 'SwiveLock Anchors'],
                                      'instrument_system': 'Arthrex Synergy Shoulder Arthroscopy System',
                                      'instruments': [{'name': 'Arthrex Cuff Repair Kit', 'quantity': 1}],
                                      'positioning': 'Beach chair position',
                                      'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                                      'sutures': ['FiberWire #2', 'SutureTape 1.3mm']},
 'Carpal Tunnel Release': {'anaesthetic': 'Interscalene Brachial Plexus Block + Light Sedation',
                           'consumables': ['Skin Marker Pen', 'Local Anaesthetic Syringe', 'Sterile Gloves'],
                           'disposables': ['Scalpel Blade #15'],
                           'drape_pack': 'Hand and Foot Aperture Drape Pack',
                           'dressings': ['Mepore', 'Crepe Bandage'],
                           'equipment': ['Stryker SmartPump Tourniquet System'],
                           'implant_system': None,
                           'implants': None,
                           'instrument_system': 'Stryker EndoBlade Carpal Tunnel Instrumentation',
                           'instruments': [{'name': 'Minor Hand Instrument Set', 'quantity': 1}],
                           'positioning': 'Supine on standard table with arm board',
                           'skin_prep': 'Betadine aqueous solution',
                           'sutures': ['Nylon 4-0']},
 'Fixation of fracture of neck of femur using intramedullary nail': {'anaesthetic': 'General Anaesthesia with '
                                                                                    'endotracheal intubation',
                                                                     'consumables': ['Skin Marker Pen',
                                                                                     'Irrigation Fluid 0.9% Saline 1L',
                                                                                     'Suction Tubing'],
                                                                     'disposables': ['Guide Wire',
                                                                                     'Disposable Drill Bit 3.2mm'],
                                                                     'drape_pack': 'Hip Fracture Drape Pack',
                                                                     'dressings': ['Aquacel Surgical'],
                                                                     'equipment': ['C-Arm Image Intensifier',
                                                                                   'Stryker System 8 Power Tool Kit'],
                                                                     'implant_system': 'DePuy Synthes TFNA '
                                                                                       'Intramedullary Line',
                                                                     'implants': ['Intramedullary Femoral Nail',
                                                                                  'Lag Screw Kit'],
                                                                     'instrument_system': 'DePuy Synthes TFNA '
                                                                                          'Insertion System',
                                                                     'instruments': [{'name': 'DePuy Synthes TFNA '
                                                                                              'Instrument Tray',
                                                                                      'quantity': 2}],
                                                                     'positioning': 'Fracture Table Positioning',
                                                                     'skin_prep': 'ChloraPrep 2% chlorhexidine '
                                                                                  'gluconate',
                                                                     'sutures': ['Vicryl 1', 'Vicryl 2-0', 'Clips']},
 'Lumbar Laminectomy': {'anaesthetic': 'General Anaesthesia with endotracheal intubation + Muscle Relaxant',
                        'consumables': ['Bone Wax', 'Irrigation Fluid 0.9% Saline 1L', 'Suction Tubing'],
                        'disposables': ['Surgical Patties', 'Disposable Burr 3.5mm'],
                        'drape_pack': 'Spine Surgical Drape Pack',
                        'dressings': ['Opsite Post-Op'],
                        'equipment': ['Midas Rex Spine Shaver / Drill', 'Jackson Spinal Surgery Table'],
                        'implant_system': None,
                        'implants': None,
                        'instrument_system': 'Caspar Lumbar Retraction Instrument Core',
                        'instruments': [{'name': 'Caspar Retractor System', 'quantity': 1}],
                        'positioning': 'Prone with Wilson frame',
                        'skin_prep': 'Betadine aqueous solution',
                        'sutures': ['Vicryl 1', 'Vicryl 2-0', 'Monocryl 3-0']},
 'MTPJ Fusion': {'anaesthetic': 'Spinal Anaesthesia with 0.5% Heavy Bupivacaine',
                 'consumables': ['Skin Marker Pen', 'Irrigation Fluid 0.9% Saline 1L', 'Suction Tubing'],
                 'disposables': ['K-wire 1.6mm', 'Disposable Drill Bit 2.0mm'],
                 'drape_pack': 'Hand and Foot Aperture Drape Pack',
                 'dressings': ['Mepore', 'Wool and Crepe'],
                 'equipment': ['Stryker SmartPump Tourniquet System'],
                 'implant_system': 'Wright Medical Foot Fusion Construct Set',
                 'implants': ['1st MTP Fusion Plate', 'Compression Screws'],
                 'instrument_system': 'Wright Medical Pro-Toe Forefoot System',
                 'instruments': [{'name': 'Small Bone Set', 'quantity': 1}],
                 'positioning': 'Supine on standard table',
                 'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                 'sutures': ['Vicryl 2-0', 'Nylon 3-0']},
 'ORIF Ankle': {'anaesthetic': 'General Anaesthesia with endotracheal intubation',
                'consumables': ['Skin Marker Pen', 'Irrigation Fluid 0.9% Saline 1L', 'Suction Tubing'],
                'disposables': ['Disposable Drill Bit 2.5mm', 'K-wire 1.6mm', 'K-wire 2.0mm'],
                'drape_pack': 'Universal Extremity Drape Pack',
                'dressings': ['Mepore', 'Wool and Crepe'],
                'equipment': ['C-Arm Image Intensifier', 'Stryker SmartPump Tourniquet System'],
                'implant_system': 'DePuy Synthes 3.5mm LCP Ankle Cluster',
                'implants': ['Distal Fibula Plate Set', 'Malleolar Screws'],
                'instrument_system': 'Synthes LCP Small Fragment Reduction Kit',
                'instruments': [{'name': 'Synthes Small Fragment Set', 'quantity': 1}],
                'positioning': 'Supine on standard table',
                'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                'sutures': ['Vicryl 2-0', 'Nylon 3-0']},
 'ORIF Tibia and Fibula': {'anaesthetic': 'General Anaesthesia with endotracheal intubation',
                           'consumables': ['Skin Marker Pen', 'Irrigation Fluid 0.9% Saline 1L', 'Suction Tubing'],
                           'disposables': ['Disposable Drill Bit 3.2mm', 'K-wire 2.0mm'],
                           'drape_pack': 'Universal Extremity Drape Pack',
                           'dressings': ['Mepore', 'Wool and Crepe'],
                           'equipment': ['C-Arm Image Intensifier', 'Stryker SmartPump Tourniquet System'],
                           'implant_system': 'DePuy Synthes 4.5mm LCP Titanium System',
                           'implants': ['Anatomic Tibia Locking Plate Set', 'Cortical Screws'],
                           'instrument_system': 'Synthes LCP Large Fragment System Trays',
                           'instruments': [{'name': 'Synthes Large Fragment Set', 'quantity': 1}],
                           'positioning': 'Supine on standard table',
                           'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                           'sutures': ['Vicryl 1', 'Vicryl 2-0', 'Nylon 3-0']},
 'Open Achilles Tendon Repair': {'anaesthetic': 'General Anaesthesia with endotracheal intubation',
                                 'consumables': ['Skin Marker Pen',
                                                 'Irrigation Fluid 0.9% Saline 1L',
                                                 'Suction Tubing'],
                                 'disposables': ['Scalpel Blade #15'],
                                 'drape_pack': 'Hand and Foot Aperture Drape Pack',
                                 'dressings': ['Mepore', 'Wool and Crepe'],
                                 'equipment': ['Stryker SmartPump Tourniquet System'],
                                 'implant_system': 'Arthrex PARS Percutaneous Achilles Assembly',
                                 'instrument_system': 'Arthrex PARS Achilles Tendon System Trays',
                                 'instruments': [{'name': 'Large Orthopaedic Set', 'quantity': 1}],
                                 'positioning': 'Prone Position',
                                 'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                                 'sutures': ['FiberWire #5', 'Vicryl 2-0', 'Nylon 3-0']},
 'Percutaneous Trigger Finger Release': {'anaesthetic': 'Local Infiltration with 1% Lignocaine',
                                         'consumables': ['Skin Marker Pen',
                                                         'Local Anaesthetic Syringe',
                                                         'Sterile Gloves'],
                                         'disposables': ['Scalpel Blade #15'],
                                         'drape_pack': 'Hand and Foot Aperture Drape Pack',
                                         'dressings': ['Mepore', 'Crepe Bandage'],
                                         'equipment': ['Stryker SmartPump Tourniquet System'],
                                         'implant_system': None,
                                         'implants': None,
                                         'instrument_system': 'Standard Open/Percutaneous Tenotomy Kit',
                                         'instruments': [{'name': 'Minor Hand Instrument Set', 'quantity': 1}],
                                         'positioning': 'Supine on standard table with arm board',
                                         'skin_prep': 'Betadine aqueous solution',
                                         'sutures': ['Nylon 4-0']},
 'Reverse Shoulder Replacement': {'anaesthetic': 'General Anaesthesia + LMA',
                                  'consumables': ['Skin Marker Pen',
                                                  'Irrigation Fluid 0.9% Saline 1L',
                                                  'Diathermy Pencil'],
                                  'disposables': ['Disposable Saw Blade - Reciprocating', 'Disposable Drill Bit 3.2mm'],
                                  'drape_pack': 'Shoulder Split Sheet Pack',
                                  'dressings': ['Mepore'],
                                  'equipment': ['Standard Diathermy Machine'],
                                  'implant_system': 'Medacta Reverse Shoulder Hardware Assembly',
                                  'implants': ['Humeral Tray', 'Glenosphere Component'],
                                  'instrument_system': 'Medacta Shoulder System Guided Instrumentation',
                                  'instruments': [{'name': 'Medacta Shoulder System (MSS)', 'quantity': 5}],
                                  'positioning': 'Beach chair position',
                                  'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                                  'sutures': ['Ethibond Excel #2', 'Vicryl 2-0', 'Monocryl 3-0']},
 'Spinal Microdiscectomy': {'anaesthetic': 'General Anaesthesia with endotracheal intubation + Muscle Relaxant',
                            'consumables': ['Surgical Patties', 'Irrigation Fluid 0.9% Saline 1L', 'Suction Tubing'],
                            'disposables': ['Disposable Burr 3.5mm'],
                            'drape_pack': 'Spine Surgical Drape Pack',
                            'dressings': ['Opsite Post-Op'],
                            'equipment': ['Midas Rex Spine Shaver / Drill', 'Jackson Spinal Surgery Table'],
                            'implant_system': None,
                            'implants': None,
                            'instrument_system': 'Medtronic METRx Microdiscectomy Instrument Tray',
                            'instruments': [{'name': 'Micro-discectomy Curettes Set', 'quantity': 1}],
                            'positioning': 'Prone with Wilson frame',
                            'skin_prep': 'Betadine aqueous solution',
                            'sutures': ['Vicryl 2-0', 'Monocryl 3-0']},
 'Thumb Carpometacarpal Joint Arthroplasty': {'anaesthetic': 'General Anaesthesia + LMA',
                                              'consumables': ['Skin Marker Pen',
                                                              'Irrigation Fluid 0.9% Saline 1L',
                                                              'Suction Tubing'],
                                              'disposables': ['K-wire 1.6mm', 'Disposable Drill Bit 2.0mm'],
                                              'drape_pack': 'Hand and Foot Aperture Drape Pack',
                                              'dressings': ['Mepore', 'Crepe Bandage'],
                                              'equipment': ['Stryker SmartPump Tourniquet System'],
                                              'implant_system': 'Acumed Total Thumb CMC System',
                                              'implants': ['Trapeziatome Spacer'],
                                              'instrument_system': 'Acumed Hand Arthroplasty Specialized Tools',
                                              'instruments': [{'name': 'Hand Arthroplasty Set', 'quantity': 1}],
                                              'positioning': 'Supine on standard table with arm board',
                                              'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                                              'sutures': ['Vicryl 2-0', 'Nylon 4-0']},
 'Total Hip Replacement (Cemented)': {'anaesthetic': 'Spinal Anaesthesia with 0.5% Heavy Bupivacaine',
                                      'consumables': ['Skin Marker Pen',
                                                      'Chlorhexidine 2% Applicator',
                                                      'Irrigation Fluid 0.9% Saline 3L',
                                                      'Pulse Lavage Tip',
                                                      'Suction Tubing',
                                                      'Diathermy Pencil',
                                                      'Light Handle Covers',
                                                      'Bone Cement Mixing Bowl Kit',
                                                      'Sterile Gloves',
                                                      'Sterile Gown'],
                                      'disposables': ['Disposable Reamer - Large',
                                                      'Cement Mixing Cartridge',
                                                      'Cement Delivery Gun Nozzle',
                                                      'Disposable Femoral Canal Brush'],
                                      'drape_pack': 'Total Hip Drape Pack',
                                      'dressings': ['Aquacel Surgical'],
                                      'equipment': ['Suction Machine', 'Diathermy Machine', 'Cement Vacuum Footpump'],
                                      'implant_system': 'R3 Acetabular / CPCS Total Hip System',
                                      'implants': ['R3 Acetabular Cup Component',
                                                   'Femoral Stem Component',
                                                   'Ceramic Head Component',
                                                   'CPCS Stem'],
                                      'instrument_system': 'R3 Acetabular System with CPCS',
                                      'instruments': [{'name': 'Smith & Nephew R3 Acetabular System', 'quantity': 4},
                                                      {'name': 'CPCS Total Hip System', 'quantity': 1},
                                                      {'name': 'Large Orthopaedic Set', 'quantity': 1},
                                                      {'name': 'Conmed PowerTools with Trinkle', 'quantity': 1},
                                                      {'name': 'Splash Bowl', 'quantity': 1},
                                                      {'name': 'Jug', 'quantity': 1},
                                                      {'name': 'Heraeus Cement Gun', 'quantity': 1}],
                                      'positioning': 'Lateral Decubitus on standard table',
                                      'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                                      'sutures': ['Vicryl 1', 'Vicryl 2-0', 'Monocryl 3-0']},
 'Total Knee Replacement': {'anaesthetic': 'Spinal Anaesthesia with 0.5% Heavy Bupivacaine',
                            'consumables': ['Skin Marker Pen',
                                            'Chlorhexidine 2% Applicator',
                                            'Irrigation Fluid 0.9% Saline 3L',
                                            'Pulse Lavage Tip',
                                            'Suction Tubing',
                                            'Diathermy Pencil',
                                            'Light Handle Covers',
                                            'Sterile Gloves',
                                            'Sterile Gown',
                                            'Sharps Pad',
                                            'Bladder Syringe',
                                            'Eschmark Bandage'],
                            'disposables': ['Disposable Saw Blade - Oscillating',
                                            'Disposable Drill Bit 3.2mm',
                                            'Cement Mixing Cartridge',
                                            'Cement Delivery Gun Nozzle'],
                            'drape_pack': 'Total Knee Arthroplasty Drape Pack',
                            'draping_order': ['Water Repellent',
                                              'Approach Drape',
                                              'Brown Stockinette (Unisurge, 15cm x 1.5m, REF: F825195)',
                                              'Plastic U drape',
                                              'Reinforced Split Sheet (200x260cm)',
                                              'Extremity Drape',
                                              'Optape x 1 (uses 2 around the glove on the ankle)',
                                              'Reinforced Adhesive Edge Drape (150x240cm)',
                                              'Reinforced Adhesive Edge Drape (150x240cm) x 2 (For the side and the '
                                              'extension for the bottom)'],
                            'dressings': ['Aquacel Surgical', 'Wool and Crepe'],
                            'equipment': ['Stryker SmartPump Tourniquet System',
                                          'Suction Machine',
                                          'Cement Vacuum Foot Pump',
                                          'Diathermy Machine'],
                            'implant_system': 'JOURNEY II BCS',
                            'implants': ['Femoral Component', 'Tibial Baseplate', 'Polyethylene Insert'],
                            'instrument_system': 'JOURNEY II BCS Knee System',
                            'instruments': [{'name': 'JOURNEY II BCS Knee System', 'quantity': 7},
                                            {'name': 'Large Orthopaedic Set', 'quantity': 1},
                                            {'name': 'Conmed PowerTools', 'quantity': 1},
                                            {'name': 'Splash Bowl', 'quantity': 1},
                                            {'name': 'Jug', 'quantity': 1},
                                            {'name': 'Heraeus Cement Gun', 'quantity': 1}],
                            'positioning': 'Supine on standard table with foot bolster',
                            'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                            'sutures': ['Vicryl 1', 'Vicryl 2-0', 'Monocryl 3-0']},
 'Total Shoulder Replacement': {'anaesthetic': 'General Anaesthesia + LMA',
                                'consumables': ['Skin Marker Pen',
                                                'Irrigation Fluid 0.9% Saline 1L',
                                                'Diathermy Pencil'],
                                'disposables': ['Disposable Saw Blade - Reciprocating', 'Disposable Drill Bit 3.2mm'],
                                'drape_pack': 'Shoulder Split Sheet Pack',
                                'dressings': ['Mepore'],
                                'equipment': ['Standard Diathermy Machine'],
                                'implant_system': 'Zimmer Biomet Comprehensive Anatomic Line',
                                'implants': ['Humeral Stem Component', 'Glenoid Base Component'],
                                'instrument_system': 'Zimmer Biomet Comprehensive Shoulder Prep Trays',
                                'instruments': [{'name': 'Zimmer Biomet Comprehensive Shoulder System', 'quantity': 3}],
                                'positioning': 'Beach chair position',
                                'skin_prep': 'ChloraPrep 2% chlorhexidine gluconate',
                                'sutures': ['Ethibond Excel #2', 'Vicryl 2-0', 'Monocryl 3-0']}}
