from __future__ import annotations

CONSUMABLES_ITEMS = ['Gauze Swabs 10x10',
 'Gauze Swabs 5x5',
 'Irrigation Fluid 0.9% Saline 1L',
 'Irrigation Fluid 0.9% Saline 3L',
 'Suction Tubing',
 'Light Handle Covers',
 'Ultrasound Gel',
 'Skin Marker Pen',
 'Chlorhexidine 2% Applicator',
 'Betadine Prep Solution',
 'Saw Blade (Conmed) x 1 Ref#5071-201',
 'Sharps Pad',
 'Scalpel Blade #10',
 'Scalpel Blade #15',
 'Suture Removal Kit',
 'Sterile Gloves (Pair)',
 'Sterile Gown',
 'Suction Yankauer Tip',
 'Diathermy Pencil',
 'Diathermy Tip',
 'Syringe 10ml',
 'Syringe 20ml',
 'Syringe 50ml',
 'Bladder Syringe',
 'Eschmark Bandage']

DISPOSABLES_ITEMS = ['K-wire 1.6mm',
 'K-wire 2.0mm',
 'Steinmann Pin 3.0mm',
 'Steinmann Pin 4.0mm',
 'Disposable Drill Bit 3.2mm',
 'Disposable Drill Bit 4.5mm',
 'Disposable Saw Blade – Oscillating',
 'Disposable Saw Blade – Reciprocating',
 'Arthroscopy Shaver Blade 4.0mm',
 'Arthroscopy Shaver Blade 5.5mm',
 'Pulse Lavage Tip',
 'Cement Mixing Cartridge',
 'Cement Delivery Gun Nozzle',
 'Disposable Trocar Set',
 'Disposable Burr 3.5mm',
 'Disposable Burr 4.0mm',
 'Disposable Reamer – Small',
 'Disposable Reamer – Large']

SUTURE_NAMES = ['Vicryl 1',
 'Vicryl 0',
 'Vicryl 2-0',
 'Vicryl 3-0',
 'PDS II 0',
 'PDS II 1',
 'PDS II 2-0',
 'Monocryl 3-0',
 'Monocryl 4-0',
 'Monocryl 5-0',
 'Prolene 3-0',
 'Prolene 4-0',
 'Ethilon 3-0',
 'Ethilon 4-0',
 'FiberWire #2',
 'FiberWire #5',
 'FiberTape 2mm',
 'SutureTape 1.3mm',
 'TigerWire #2',
 'Ethibond Excel #2',
 'Ethibond Excel #5',
 'Ti-Cron #2']

DRESSING_OPTIONS = ['Mepitel',
 'Adaptic',
 'Jelonet',
 'Mepore',
 'Melolin',
 'Primapore',
 'Opsite Post-Op',
 'Opsite Flexifix',
 'Aquacel Surgical',
 'Aquacel Ag',
 'Tegaderm Foam',
 'Steri-Strips 6mm',
 'Steri-Strips 12mm',
 'Crepe Bandage',
 'Wool and Crepe',
 'Tubigrip Size B',
 'Tubigrip Size C']
